Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print("This program calculates and displays travel expenses\n")
... 
... 
... budget = float(input("Enter Budget: "))
... 
... 
... destination = input("\nEnter your travel destination: ")
... 
... 
... gas = float(input("\nHow much do you think you will spend on gas? "))
... 
... 
... accomodation = float(input("\nApproximately, how much will you need for accomodation/hotel? "))
... 
... 
... food = float(input("\nLast, how much do you need for food? "))
... 
... print("\n------------Travel Expenses------------")
... 
... print("Location:",destination)
... print("Initial Budget:",budget)
... print("\nFuel:",gas)
... print("Accomodation:",accomodation)
... print("Food",food)
... 
... 
... balance = budget - gas - accomodation - food
... 
... 
